import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="p-3 bg-gray-50 flex gap-5 items-center">
          <Link className="text-2xl font-bold" href={"/"}>Next 15</Link>
          <nav className="flex">
            <Link className="text-sm text-blue-500" href={"/posts"}>posts</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
